names:
  - parse
  - 10x

count_adata:
  parse: /path/to/parse.h5ad
  10x: /path/to/10x.h5ad

n_topics:
  - 5
  - 10

organism: mouse
workdir: ./results

train:
  backend: default
  device: auto
  dtype: float32
  publish_single_runs: true
  random_states:
    - 0
    - 1
    - 2
  batch_size: 128
  max_iter: 5
  n_jobs: 1

top_model:
  n_top_genes: null
  resolution: 1
  max_iter_harmony: 10
  min_cell_participation: null

plotting:
  interactive: false

merge: true