names:
  - igvf_full

count_adata:
  igvf_full: ./tutorials/IGVFFI3320ZCCE/IGVFFI3320ZCCE.h5ad

n_topics:
  - 5
  - 10
  - 15
  - 20

organism: human
workdir: ./results/igvf_full

train:
  backend: default
  device: auto
  dtype: float32
  publish_single_runs: true
  random_states:
    - 0
    - 1
  batch_size: 256
  max_iter: 5
  n_jobs: 1

top_model:
  n_top_genes: 100
  resolution: 1
  max_iter_harmony: 5
  min_cell_participation: null

plotting:
  interactive: false

merge: false