from scripts.make_train import *
from scripts.make_topmodel import *

configfile: "config/config.yaml"

n_topics = config['n_topics']

##### load rules #####
include: "rules/train.smk"
include: "rules/topModel.smk"


# ##### make neccessary directories #####
# for name in config['names']:
#     for n_topic in config['n_topics']:
#         # Check if the file exists
#         if not os.path.exists(f"{config['workdir']}/{name}/{n_topic}/train"):
#             os.makedirs(f"{config['workdir']}/{name}/{n_topic}/train", mode=0o777)
#
#         if not os.path.exists(f"{config['workdir']}/{name}/{n_topic}/topmodel"):
#             os.makedirs(f"{config['workdir']}/{name}/{n_topic}/topmodel", mode=0o777)

#### check if merging is necessary ###
merging = []
if 'merge' in config:
    merging = [f"{config['workdir']}/topModel_{'_'.join(config['names'])}.p",
               f"{config['workdir']}/analysis_{'_'.join(config['names'])}.p"]


##### target rules #####
rule all:
    input:
        expand(f"{config['workdir']}/{{name}}/{{n_topic}}/train/train_{{name}}_{{n_topic}}_{{random_state}}.p",
            name=config["names"],
            n_topic=config["n_topics"],
            random_state=config["train"]["random_states"]),
        expand(f"{config['workdir']}/{{name}}/{{n_topic}}/train/train_{{name}}_{{n_topic}}.p",
            name=config['names'],
            n_topic=config["n_topics"]),
        expand(f"{config['workdir']}/{{name}}/{{n_topic}}/topmodel/topModel_{{name}}_{{n_topic}}.p",
            name=config['names'],
            n_topic=config["n_topics"]),
        expand(f"{config['workdir']}/{{name}}/{{n_topic}}/topmodel/analysis_{{name}}_{{n_topic}}.p",
            name=config['names'],
            n_topic=config["n_topics"]),
        merging,
